export const LOGIN = "LOGIN";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";

export const REGISTER = "REGISTER";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAILURE = "REGISTER_FAILURE";

export const CURRENT_USER = "CURRENT_USER";
export const CURRENT_USER_SUCCESS = "CURRENT_USER_SUCCES";
export const CURRENT_USER_FAILURE = "CURRENT_USER_FAILURE";

export const LOGOUT = "LOGOUT";

export const TESTAPI = "TESTAPI";
export const TESTAPI_SUCCESS = "TESTAPI_SUCCESS";
export const TESTAPI_FAIL = "TESTAPI_FAIL";


export const LOAD_SETTINGS = "LOAD_SETTINGS";
export const OTP_REQUEST = "OTP_REQUEST";

export const LOAD_LOCATION = "LOAD_LOCATION";

export const LOAD_SELLERS = "LOAD_SELLERS";

export const SET_ACTIVE_SELLER = "SET_ACTIVE_SELLER";

export const SELLER_LOADING="SELLER_LOADING";

export const ADD_TO_CART="ADD_TO_CART";
export const LOAD_CART="LOAD_CART";
export const REMOVE_FROM_CART="REMOVE_FROM_CART";